name: Build CV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build CV
      run: docker build --file Dockerfile --tag my-cv:$(date +%s) --output pdf .
    - name: see list
      run: ls -lah
    - name: Upload PDF
      uses: actions/upload-artifact@v3
      with:
        name: my-cv-pdf
        if-no-files-found: error
        path: .
