name: Build CV

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build CV
      run: docker buildx build --file Dockerfile --tag my-cv:$(date +%s) --output pdf .
    - name: List Files
      run: ls -lah pdf
    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: my-cv-pdf
        if-no-files-found: error
        path: pdf/main.pdf
    - name: Push CV to Repo
      run: |
          git config --global user.name 'Please Please Moar Smart Names'
          git config --global user.email 'Vera-Kovaleva@users.noreply.github.com'
          git add pdf/main.pdf
          git commit -am "Automated Publish"
          git push -f --set-upstream resume-ipr-public main
