name: Build and deploy latex sources to GitHub Pages

on: push

jobs:

  build:

    runs-on: debian:10.3

    steps:

    - uses: actions/checkout@v2

    - name: Build document

      uses: xu-cheng/latex-action@v2

      with:

        root_file: main.tex

        working_directory: cv/

        args: -interaction=nonstopmode

        compiler: pdflatex

    - name: Upload pdf document

      uses: actions/upload-artifact@v2

      with:

        name: main

        path: cv/main.pdf
